services:
  productionplan:
    build: 
      context: .
    image: productionplan
    networks:
      - engie
    ports:
      - 8888:8888
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_DEBUG: true
    restart: unless-stopped
    
networks:
  engie:
    name: engie
